// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3msFyxMQ5PVhWwtrI8kFHj5jUugdgdyY',
    appId: '1:125532263888:web:44f0a0e14c6b7e31a115d5',
    messagingSenderId: '125532263888',
    projectId: 'eventlyapp-c8650',
    authDomain: 'eventlyapp-c8650.firebaseapp.com',
    storageBucket: 'eventlyapp-c8650.firebasestorage.app',
    measurementId: 'G-JZX0YY7NJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7ht8w6Vbw11qjOInlUJ6TAoOr9RBUPI',
    appId: '1:125532263888:android:6799a8e029c7057ea115d5',
    messagingSenderId: '125532263888',
    projectId: 'eventlyapp-c8650',
    storageBucket: 'eventlyapp-c8650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHLabrSpUSIs7cuTM2uexiU84xBhujtZ4',
    appId: '1:125532263888:ios:4497c66a0a004ccda115d5',
    messagingSenderId: '125532263888',
    projectId: 'eventlyapp-c8650',
    storageBucket: 'eventlyapp-c8650.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHLabrSpUSIs7cuTM2uexiU84xBhujtZ4',
    appId: '1:125532263888:ios:4497c66a0a004ccda115d5',
    messagingSenderId: '125532263888',
    projectId: 'eventlyapp-c8650',
    storageBucket: 'eventlyapp-c8650.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3msFyxMQ5PVhWwtrI8kFHj5jUugdgdyY',
    appId: '1:125532263888:web:2efb68ec40a72429a115d5',
    messagingSenderId: '125532263888',
    projectId: 'eventlyapp-c8650',
    authDomain: 'eventlyapp-c8650.firebaseapp.com',
    storageBucket: 'eventlyapp-c8650.firebasestorage.app',
    measurementId: 'G-1V54T4J1QH',
  );
}
